<?php

use Illuminate\Database\Seeder;

class MathesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('matches')->delete();

        $matches = [
            [
                'host_photo' => 'host_photo_empty.png',
                'host_name' => 'Bishop',
                'title' => 'Football',
                'start_time' => '2020-06-23 10:00:00',
                "address" => "Proact Stadium - home to Chesterfield FC, Sheffield Road, Chesterfield",
                "latitude" => 53.2535714,
                "longitude" => -1.4257437,
                'max_players' => 12,
                'rules' => '6 VS 6',
                'reservations' => 0,
                'active' => 1,
                'credits' => 10,
            ],
            [
                'host_photo' => 'host_photo_empty.png',
                'host_name' => 'Chatillon',
                'title' => 'Football',
                'start_time' => '2020-06-22 21:21:26',
                "address" => "Manchester City Football Match Day Ticket Sales, Ashton New Road, Manchester",
                "latitude" => 53.4841079,
                "longitude" => -2.200671,
                'max_players' => 14,
                'rules' => '7 VS 7',
                'reservations' => 0,
                'active' => 1,
                'credits' => 10,
            ],
            [
                'host_photo' => 'host_photo_empty.png',
                'host_name' => 'Ethelwolf',
                'title' => 'Football',
                'start_time' => '2020-06-22 16:00:00',
                "address" => "Peninsula Stadium, Moor Lane, Salford",
                "latitude" => 53.51363499,
                "longitude" => -2.2767797,
                'max_players' => 22,
                'rules' => '11 VS 11',
                'reservations' => 0,
                'active' => 1,
                'credits' => 10,
            ],
            [
                'host_photo' => 'host_photo_empty.png',
                'host_name' => 'Gomer',
                'title' => 'Football',
                'start_time' => '2020-06-24 10:30:00',
                "address" => "Bury Football Stadium, Gigg Lane, Bury",
                "latitude" => 53.5805097,
                "longitude" => -2.2948209,
                'max_players' => 18,
                'rules' => '9 VS 9',
                'reservations' => 0,
                'active' => 1,
                'credits' => 10,
            ],
            [
                'host_photo' => 'host_photo_empty.png',
                'host_name' => 'Hickory',
                'title' => 'Football',
                'start_time' => '2020-06-20 16:30:00',
                "address" => "University of Bolton Stadium, Burnden Way, Horwich, Bolton",
                "latitude" => 53.5813723,
                "longitude" => -2.5369749,
                'max_players' => 12,
                'rules' => '6 VS 6',
                'reservations' => 0,
                'active' => 1,
                'credits' => 10,
            ],
            [
                'host_photo' => 'host_photo_empty.png',
                'host_name' => 'Keaton',
                'title' => 'Football',
                'start_time' => '2020-06-15 09:30:00',
                "address" => "DW Stadium, Loire Drive, Robin Park Road, Wigan",
                "latitude" => 53.5476804,
                "longitude" => -2.6541071,
                'max_players' => 16,
                'rules' => '8 VS 8',
                'reservations' => 0,
                'active' => 1,
                'credits' => 10,
            ],
            [
                'host_photo' => 'host_photo_empty.png',
                'host_name' => 'Locke',
                'title' => 'Football',
                'start_time' => '2020-06-24 09:30:00',
                "address" => "Blackburn Rovers, Blackburn",
                "latitude" => 53.7286169,
                "longitude" => -2.4891799,
                'max_players' => 12,
                'rules' => '6 VS 6',
                'reservations' => 0,
                'active' => 1,
                'credits' => 10,
            ],
            [
                'host_photo' => 'host_photo_empty.png',
                'host_name' => 'Pacey',
                'title' => 'Football',
                'start_time' => '2020-06-27 10:00:00',
                "address" => "Crown Ground, Livingstone Road, Accrington",
                "latitude" => 53.76523359999999,
                "longitude" => -2.3708631,
                'max_players' => 10,
                'rules' => '5 VS 5',
                'reservations' => 0,
                'active' => 1,
                'credits' => 10,
            ],
            [
                'host_photo' => 'host_photo_empty.png',
                'host_name' => 'Richard',
                'title' => 'Football',
                'start_time' => '2020-06-14 17:00:00',
                "address" => "Burnley Football Club, Harry Potts Way, Burnley",
                "latitude" => 53.788987,
                "longitude" => -2.230187,
                'max_players' => 18,
                'rules' => '9 VS 9',
                'reservations' => 0,
                'active' => 1,
                'credits' => 10,
            ],
            [
                'host_photo' => 'host_photo_empty.png',
                'host_name' => 'Woodis',
                'title' => 'Football',
                'start_time' => '2020-06-13 15:00:00',
                "address" => "Elland Road, Elland Road, Beeston, Leeds",
                "latitude" => 53.7778162,
                "longitude" => -1.5721446,
                'max_players' => 12,
                'rules' => '6 VS 6',
                'reservations' => 0,
                'active' => 1,
                'credits' => 10,
            ],
        ];

        DB::table('matches')->insert($matches);
    }
}
